### ISSUE TITLE
Future.

### ISSUE THREAD

**Issue by juliolitwin** [RomanZhu/Frame-Number-Sync#1]
Yo @RomanZhu,

In a note, you said you would try to improve the sync, do you still think about doing it?
Thanks for the project, it helped me a lot.

Regards,
Julio Litwin.

**Comment by RomanZhu** [comment]
Yes, but it is part of another project

**Comment by juliolitwin** [comment]
Thanks for answering me @RomanZhu, is it a public project?

**Comment by RomanZhu** [comment]
No, but that part can end up being public (can't say any ETA)

**Comment by juliolitwin** [comment]
Thank you, I'll be waiting for you when you publish. :)
